server:
  port: 25565
spring:
  application:
    name: customs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/freight-customs?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.prprv.customs.controller
logging:
  level:
    root: info
  file:
    name: ./logs/${spring.application.name}.log
  pattern:
    file: H %d{yyyy-MM-dd HH:mm:ss.SSS} %p %C.%M %m %n
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

